import { contextBridge, ipcRenderer, webUtils } from "electron/renderer";
import { randomUUID } from "node:crypto";

const on = (channel, callback) => {
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.off(channel, listener);
};

const binanceMarketStreamCallbacks = new Map();
ipcRenderer.on("binanceMarket:streamEvent", (_event, payload = {}) => {
  const callback = binanceMarketStreamCallbacks.get(String(payload.subscriptionId || ""));
  if (callback) callback(payload.event);
});

async function subscribeBinanceMarketStreams(params, callback) {
  if (typeof callback !== "function") throw new TypeError("Binance market stream callback is required");
  const subscriptionId = `renderer-market-${randomUUID()}`;
  binanceMarketStreamCallbacks.set(subscriptionId, callback);
  try {
    await ipcRenderer.invoke("binanceMarket:streamSubscribe", { ...params, subscriptionId });
    return { subscriptionId };
  } catch (error) {
    binanceMarketStreamCallbacks.delete(subscriptionId);
    throw error;
  }
}

async function unsubscribeBinanceMarketStreams(params = {}) {
  const subscriptionId = String(params.subscriptionId || "");
  binanceMarketStreamCallbacks.delete(subscriptionId);
  return ipcRenderer.invoke("binanceMarket:streamUnsubscribe", { subscriptionId });
}

async function invokeBinanceAccountSnapshot(params) {
  const result = await ipcRenderer.invoke("binanceAccount:getSnapshot", params);
  if (result?.ok === true) return result.snapshot;
  if (result?.ok === false && result.error) {
    const error = new Error(String(result.error.message || "Binance 账户数据读取失败。"));
    error.name = "BinanceAccountError";
    error.code = String(result.error.code || "BINANCE_REQUEST_FAILED");
    error.retryable = result.error.retryable === true;
    const retryAfterMs = Number(result.error.retryAfterMs);
    if (Number.isFinite(retryAfterMs) && retryAfterMs > 0) error.retryAfterMs = retryAfterMs;
    throw error;
  }
  // Backward compatibility for a main process from before the response envelope.
  return result;
}

async function invokeBinanceAccountProfitCalendar(params) {
  const result = await ipcRenderer.invoke("binanceAccount:getProfitCalendar", params);
  if (result?.ok === true) return result.calendar;
  if (result?.ok === false && result.error) {
    const error = new Error(String(result.error.message || "Binance 收益日历读取失败。"));
    error.name = "BinanceAccountError";
    error.code = String(result.error.code || "BINANCE_REQUEST_FAILED");
    error.retryable = result.error.retryable === true;
    const retryAfterMs = Number(result.error.retryAfterMs);
    if (Number.isFinite(retryAfterMs) && retryAfterMs > 0) error.retryAfterMs = retryAfterMs;
    throw error;
  }
  return result;
}

contextBridge.exposeInMainWorld("codexDesktop", {
  platform: process.platform,
  start: () => ipcRenderer.invoke("codex:start"),
  getStatus: () => ipcRenderer.invoke("codex:getStatus"),
  getDefaults: () => ipcRenderer.invoke("codex:getDefaults"),
  getSystemIntegrationState: () => ipcRenderer.invoke("desktop:getSystemIntegrationState"),
  setSystemIntegration: (params) => ipcRenderer.invoke("desktop:setSystemIntegration", params),
  setTaskCompletionPopupEnabled: (params) => ipcRenderer.invoke("app:setTaskCompletionPopupEnabled", params),
  confirmTaskCompletionRendered: (params) => ipcRenderer.invoke("app:confirmTaskCompletionRendered", params),
  notifyExecutionPlanStatusChanged: (params) => ipcRenderer.invoke("app:notifyExecutionPlanStatusChanged", params),
  createExecutionPlanSticky: (params) => ipcRenderer.invoke("executionPlanSticky:create", params),
  setTaskbarUnreadCount: (params) => ipcRenderer.invoke("app:setTaskbarUnreadCount", params),
  setAppTheme: (params) => ipcRenderer.invoke("app:setTheme", params),
  setAppLanguage: (params) => ipcRenderer.invoke("app:setLanguage", params),
  checkWindowsUpdate: (params) => ipcRenderer.invoke("app:checkWindowsUpdate", params),
  downloadWindowsUpdate: (params) => ipcRenderer.invoke("app:downloadWindowsUpdate", params),
  resolveThreadGroupWorkspace: (params) => ipcRenderer.invoke("app:resolveThreadGroupWorkspace", params),
  listThreadGroupWorkspaces: (params) => ipcRenderer.invoke("app:listThreadGroupWorkspaces", params),
  openThreadGroupFolder: (params) => ipcRenderer.invoke("app:openThreadGroupFolder", params),
  pickThreadGroupFolder: () => ipcRenderer.invoke("app:pickThreadGroupFolder"),
  pickComposerFilesAndFolders: () => ipcRenderer.invoke("app:pickComposerFilesAndFolders"),
  createThreadGroupFolder: (params) => ipcRenderer.invoke("app:createThreadGroupFolder", params),
  // HAOLO-TURN-DIAGNOSTICS-BEGIN: removable report export bridge
  exportDiagnostics: () => ipcRenderer.invoke("app:exportDiagnostics"),
  // HAOLO-TURN-DIAGNOSTICS-END: removable report export bridge
  exportUserData: (params) => ipcRenderer.invoke("app:exportUserData", params),
  importUserData: (params) => ipcRenderer.invoke("app:importUserData", params),
  resolveAppConfirmation: (params) => ipcRenderer.invoke("app:confirmation-resolve", params),
  getUserDataTransferStatus: () => ipcRenderer.invoke("app:getUserDataTransferStatus"),
  quitApp: () => ipcRenderer.invoke("app:quit"),
  getYouleSession: () => ipcRenderer.invoke("youle:getSession"),
  refreshYouleSession: (params) => ipcRenderer.invoke("youle:refreshSession", params),
  openWebsiteSupport: () => ipcRenderer.invoke("youle:openWebsiteSupport"),
  refreshProfile: () => ipcRenderer.invoke("youle:refreshProfile"),
  listImageGenerationModels: (params) =>
    ipcRenderer.invoke("youle:listImageGenerationModels", params),
  listProviderModelCatalog: (params) =>
    ipcRenderer.invoke("youle:listProviderModelCatalog", params),
  listBusinessModelPools: (params) =>
    ipcRenderer.invoke("youle:listBusinessModelPools", params),
  refreshSub2ApiAccount: () => ipcRenderer.invoke("youle:refreshSub2ApiAccount"),
  getGitHubConnectionStatus: () => ipcRenderer.invoke("youle:getGitHubConnectionStatus"),
  startGitHubAuthorization: () => ipcRenderer.invoke("youle:startGitHubAuthorization"),
  disconnectGitHub: () => ipcRenderer.invoke("youle:disconnectGitHub"),
  getSubscriptionBalanceDetails: () => ipcRenderer.invoke("youle:getSubscriptionBalanceDetails"),
  createWeb3PaymentOrder: (params) => ipcRenderer.invoke("youle:createWeb3PaymentOrder", params),
  getWeb3PaymentOrder: (params) => ipcRenderer.invoke("youle:getWeb3PaymentOrder", params),
  listWeb3RechargeHistory: (params) => ipcRenderer.invoke("youle:listWeb3RechargeHistory", params),
  refreshMemberLevel: () => ipcRenderer.invoke("youle:refreshMemberLevel"),
  sendActivityHeartbeat: (params) => ipcRenderer.invoke("youle:sendActivityHeartbeat", params),
  reportTaskCompleted: (params) => ipcRenderer.invoke("youle:reportTaskCompleted", params),
  reportConsumptionAppEntry: () => ipcRenderer.invoke("youle:reportConsumptionAppEntry"),
  reportConsumptionEvent: (params) => ipcRenderer.invoke("youle:reportConsumptionEvent", params),
  getConsumptionOverview: (params) => ipcRenderer.invoke("youle:getConsumptionOverview", params),
  getConsumptionCalendar: (params) => ipcRenderer.invoke("youle:getConsumptionCalendar", params),
  syncConsumptionHistory: (params) => ipcRenderer.invoke("youle:syncConsumptionHistory", params),
  getConsumptionRecords: (params) => ipcRenderer.invoke("youle:getConsumptionRecords", params),
  exportConsumptionReport: (params) => ipcRenderer.invoke("youle:exportConsumptionReport", params),
  login: (params) => ipcRenderer.invoke("youle:login", params),
  lookupIdentity: (params) => ipcRenderer.invoke("youle:lookupIdentity", params),
  sendOtp: (params) => ipcRenderer.invoke("youle:sendOtp", params),
  verifyOtp: (params) => ipcRenderer.invoke("youle:verifyOtp", params),
  getBinancePublicMarketData: (params) => ipcRenderer.invoke("binanceMarket:publicGet", params),
  cancelBinancePublicMarketData: (params) => ipcRenderer.invoke("binanceMarket:publicCancel", params),
  subscribeBinanceMarketStreams: (params, callback) => subscribeBinanceMarketStreams(params, callback),
  unsubscribeBinanceMarketStreams: (params) => unsubscribeBinanceMarketStreams(params),
  getHyperliquidPublicCandles: (params) => ipcRenderer.invoke("hyperliquidMarket:candles", params),
  getBinanceAccountStatus: () => ipcRenderer.invoke("binanceAccount:getStatus"),
  sendBinanceAccountOtp: () => ipcRenderer.invoke("binanceAccount:sendOtp"),
  bindBinanceAccount: (params) => ipcRenderer.invoke("binanceAccount:bind", params),
  getBinanceAccountSnapshot: (params) => invokeBinanceAccountSnapshot(params),
  getBinanceAccountProfitCalendar: (params) => invokeBinanceAccountProfitCalendar(params),
  removeBinanceAccount: (params) => ipcRenderer.invoke("binanceAccount:remove", params),
  completeRegistration: (params) => ipcRenderer.invoke("youle:completeRegistration", params),
  getWechatAuthConfig: (params) => ipcRenderer.invoke("youle:getWechatAuthConfig", params),
  startWechatAuthFlow: (params) => ipcRenderer.invoke("youle:startWechatAuthFlow", params),
  getWechatAuthFlowStatus: (params) => ipcRenderer.invoke("youle:getWechatAuthFlowStatus", params),
  exchangeWechatAuthFlow: (params) => ipcRenderer.invoke("youle:exchangeWechatAuthFlow", params),
  validateInvite: (params) => ipcRenderer.invoke("youle:validateInvite", params),
  validateVideoExpertAccess: (params) => ipcRenderer.invoke("youle:validateVideoExpertAccess", params),
  listVideoExpertModels: (params) =>
    ipcRenderer.invoke("youle:listVideoExpertModels", params),
  logout: () => ipcRenderer.invoke("youle:logout"),
  patchProfile: (params) => ipcRenderer.invoke("youle:patchProfile", params),
  listConversations: (params) => ipcRenderer.invoke("youle:listConversations", params),
  listPromptFavorites: (params) => ipcRenderer.invoke("youle:listPromptFavorites", params),
  createPromptFavorite: (params) => ipcRenderer.invoke("youle:createPromptFavorite", params),
  updatePromptFavorite: (params) => ipcRenderer.invoke("youle:updatePromptFavorite", params),
  deletePromptFavorite: (params) => ipcRenderer.invoke("youle:deletePromptFavorite", params),
  patchConversationPreferences: (params) => ipcRenderer.invoke("youle:patchConversationPreferences", params),
  deleteConversation: (params) => ipcRenderer.invoke("youle:deleteConversation", params),
  listChannels: (params) => ipcRenderer.invoke("youle:listChannels", params),
  createChannel: (params) => ipcRenderer.invoke("youle:createChannel", params),
  getChannel: (params) => ipcRenderer.invoke("youle:getChannel", params),
  updateChannel: (params) => ipcRenderer.invoke("youle:updateChannel", params),
  leaveChannel: (params) => ipcRenderer.invoke("youle:leaveChannel", params),
  listChannelParticipants: (params) => ipcRenderer.invoke("youle:listChannelParticipants", params),
  addChannelParticipant: (params) => ipcRenderer.invoke("youle:addChannelParticipant", params),
  updateChannelParticipant: (params) => ipcRenderer.invoke("youle:updateChannelParticipant", params),
  removeChannelParticipant: (params) => ipcRenderer.invoke("youle:removeChannelParticipant", params),
  listChannelMessages: (params) => ipcRenderer.invoke("youle:listChannelMessages", params),
  sendChannelMessage: (params) => ipcRenderer.invoke("youle:sendChannelMessage", params),
  prepareGroupChatContext: (params) => ipcRenderer.invoke("youle:prepareGroupChatContext", params),
  sendProviderChat: (params) => ipcRenderer.invoke("youle:sendProviderChat", params),
  interruptProviderChat: (params) => ipcRenderer.invoke("youle:interruptProviderChat", params),
  onQuestionAnswerProgress: (callback) => on("questionAnswer:progress", callback),
  onQuestionAnswerStream: (callback) => on("questionAnswer:stream", callback),
  startWorkflowRun: (params) => ipcRenderer.invoke("workflow:startRun", params),
  startWorkflowSpecRun: (params) => ipcRenderer.invoke("workflow:startSpecRun", params),
  getWorkflowRun: (params) => ipcRenderer.invoke("workflow:getRun", params),
  getLatestWorkflowRunForThread: (params) => ipcRenderer.invoke("workflow:getLatestForThread", params),
  cancelWorkflowRun: (params) => ipcRenderer.invoke("workflow:cancelRun", params),
  createWorkflowRevisionDraft: (params) => ipcRenderer.invoke("workflow:createRevisionDraft", params),
  getWorkflowRevisionDraft: (params) => ipcRenderer.invoke("workflow:getRevisionDraft", params),
  compileWorkflowRevisionNode: (params) => ipcRenderer.invoke("workflow:compileRevisionNode", params),
  applyWorkflowRevisionCommand: (params) => ipcRenderer.invoke("workflow:applyRevisionCommand", params),
  saveWorkflowRevisionLayout: (params) => ipcRenderer.invoke("workflow:saveRevisionLayout", params),
  validateWorkflowRevisionDraft: (params) => ipcRenderer.invoke("workflow:validateRevisionDraft", params),
  freezeWorkflowRevisionDraft: (params) => ipcRenderer.invoke("workflow:freezeRevisionDraft", params),
  getWorkflowSpec: (params) => ipcRenderer.invoke("workflow:getSpec", params),
  listReusableWorkflowSpecs: (params) => ipcRenderer.invoke("workflow:listReusableSpecs", params),
  onWorkflowEvent: (callback) => on("workflow:event", callback),
  listExternalModelProviders: () => ipcRenderer.invoke("externalModels:listProviders"),
  saveExternalModelProvider: (params) => ipcRenderer.invoke("externalModels:saveProvider", params),
  removeExternalModelProvider: (params) => ipcRenderer.invoke("externalModels:removeProvider", params),
  testExternalModelConnection: (params) => ipcRenderer.invoke("externalModels:testConnection", params),
  listTradingStrategies: () => ipcRenderer.invoke("tradingStrategy:list"),
  listPersonalStrategies: (params) => ipcRenderer.invoke("personalStrategy:list", params),
  preparePersonalStrategySource: (params) => ipcRenderer.invoke("personalStrategy:prepareSource", params),
  createPersonalStrategyDraft: (params) => ipcRenderer.invoke("personalStrategy:createDraft", params),
  simulatePersonalStrategy: (params) => ipcRenderer.invoke("personalStrategy:simulate", params),
  confirmPersonalStrategy: (params) => ipcRenderer.invoke("personalStrategy:confirm", params),
  givePersonalStrategyFeedback: (params) => ipcRenderer.invoke("personalStrategy:feedback", params),
  classifyTradingStrategyRequest: (params) => ipcRenderer.invoke("tradingStrategy:classify", params),
  classifyExternalTradingRequest: (params) => ipcRenderer.invoke("tradingStrategy:classifyExternal", params),
  runTradingStrategyAnalysis: (params) => ipcRenderer.invoke("tradingStrategy:run", params),
  cancelTradingStrategyAnalysis: (params = {}) => ipcRenderer.invoke("tradingStrategy:cancel", params),
  classifyTradingChanRequest: (params) => ipcRenderer.invoke("tradingAnalysis:classifyChanRequest", params),
  runTradingChanTest: (params) => ipcRenderer.invoke("tradingAnalysis:runChanTest", params),
  classifyTradingOrderFlowRequest: (params) => ipcRenderer.invoke("tradingAnalysis:classifyOrderFlowRequest", params),
  runTradingOrderFlowAnalysis: (params) => ipcRenderer.invoke("tradingAnalysis:runOrderFlow", params),
  classifyTradingWaveRequest: (params) => ipcRenderer.invoke("tradingAnalysis:classifyWaveRequest", params),
  runTradingWaveAnalysis: (params) => ipcRenderer.invoke("tradingAnalysis:runWave", params),
  classifyTradingWyckoffRequest: (params) => ipcRenderer.invoke("tradingAnalysis:classifyWyckoffRequest", params),
  runTradingWyckoffAnalysis: (params) => ipcRenderer.invoke("tradingAnalysis:runWyckoff", params),
  classifyTradingGeneralRequest: (params) => ipcRenderer.invoke("tradingAnalysis:classifyGeneralRequest", params),
  runTradingGeneralAnalysis: (params) => ipcRenderer.invoke("tradingAnalysis:runGeneral", params),
  recordTradingAnalysisFailure: (params) => ipcRenderer.invoke("tradingAnalysis:recordFailure", params),
  cancelTradingAnalysis: (params = {}) => ipcRenderer.invoke("tradingAnalysis:cancel", params),
  getFinnhubMarketDataStatus: () => ipcRenderer.invoke("marketData:getFinnhubStatus"),
  searchFinnhubMarkets: (params) => ipcRenderer.invoke("marketData:searchFinnhub", params),
  getFinnhubMarketQuotes: (params) => ipcRenderer.invoke("marketData:getFinnhubQuotes", params),
  getPublicMarketIndices: () => ipcRenderer.invoke("marketData:getPublicIndices"),
  getFinnhubMarketSnapshot: (params) => ipcRenderer.invoke("marketData:getFinnhubSnapshot", params),
  getFinnhubMarketCandles: (params) => ipcRenderer.invoke("marketData:getFinnhubCandles", params),
  getIfindMarketDataStatus: () => ipcRenderer.invoke("marketData:getIfindStatus"),
  searchIfindMarkets: (params) => ipcRenderer.invoke("marketData:searchIfind", params),
  getIfindMarketQuotes: (params) => ipcRenderer.invoke("marketData:getIfindQuotes", params),
  getIfindMarketSnapshot: (params) => ipcRenderer.invoke("marketData:getIfindSnapshot", params),
  getIfindMarketCandles: (params) => ipcRenderer.invoke("marketData:getIfindCandles", params),
  getExternalAgentCapabilities: () => ipcRenderer.invoke("externalAgents:getCapabilities"),
  startExternalAgentRun: (params) => ipcRenderer.invoke("externalAgents:startRun", params),
  getExternalAgentRun: (params) => ipcRenderer.invoke("externalAgents:getRun", params),
  waitExternalAgentRun: (params) => ipcRenderer.invoke("externalAgents:waitRun", params),
  cancelExternalAgentRun: (params) => ipcRenderer.invoke("externalAgents:cancelRun", params),
  onExternalAgentEvent: (callback) => on("externalAgents:event", callback),
  loadProviderChatThreads: () => ipcRenderer.invoke("youle:loadProviderChatThreads"),
  saveProviderChatThreads: (params) => ipcRenderer.invoke("youle:saveProviderChatThreads", params),
  claimChannelAgentMessage: (params) => ipcRenderer.invoke("youle:claimChannelAgentMessage", params),
  updateChannelMessage: (params) => ipcRenderer.invoke("youle:updateChannelMessage", params),
  deleteChannelMessage: (params) => ipcRenderer.invoke("youle:deleteChannelMessage", params),
  markChannelRead: (params) => ipcRenderer.invoke("youle:markChannelRead", params),
  searchChannelUsers: (params) => ipcRenderer.invoke("youle:searchChannelUsers", params),
  searchContacts: (params) => ipcRenderer.invoke("youle:searchContacts", params),
  listContacts: (params) => ipcRenderer.invoke("youle:listContacts", params),
  getContact: (params) => ipcRenderer.invoke("youle:getContact", params),
  updateContact: (params) => ipcRenderer.invoke("youle:updateContact", params),
  deleteContact: (params) => ipcRenderer.invoke("youle:deleteContact", params),
  openContactChannel: (params) => ipcRenderer.invoke("youle:openContactChannel", params),
  listContactRequests: (params) => ipcRenderer.invoke("youle:listContactRequests", params),
  createContactRequest: (params) => ipcRenderer.invoke("youle:createContactRequest", params),
  acceptContactRequest: (params) => ipcRenderer.invoke("youle:acceptContactRequest", params),
  rejectContactRequest: (params) => ipcRenderer.invoke("youle:rejectContactRequest", params),
  cancelContactRequest: (params) => ipcRenderer.invoke("youle:cancelContactRequest", params),
  archiveContactRequest: (params) => ipcRenderer.invoke("youle:archiveContactRequest", params),
  archiveHandledContactRequests: (params) => ipcRenderer.invoke("youle:archiveHandledContactRequests", params),
  ensureExternalChannelsBackend: () => ipcRenderer.invoke("youle:ensureExternalChannelsBackend"),
  listExternalChannels: () => ipcRenderer.invoke("youle:listExternalChannels"),
  startExternalChannelLogin: (params) => ipcRenderer.invoke("youle:startExternalChannelLogin", params),
  getExternalChannelLogin: (params) => ipcRenderer.invoke("youle:getExternalChannelLogin", params),
  bindExternalChannelThread: (params) => ipcRenderer.invoke("youle:bindExternalChannelThread", params),
  listExternalChannelMessages: (params) => ipcRenderer.invoke("youle:listExternalChannelMessages", params),
  showExternalChannelAttention: (params) => ipcRenderer.invoke("youle:showExternalChannelAttention", params),
  replyExternalChannelMessage: (params) => ipcRenderer.invoke("youle:replyExternalChannelMessage", params),
  disconnectExternalChannel: (params) => ipcRenderer.invoke("youle:disconnectExternalChannel", params),
  startChannelEvents: (params) => ipcRenderer.invoke("youle:startChannelEvents", params),
  stopChannelEvents: () => ipcRenderer.invoke("youle:stopChannelEvents"),
  listMaterials: (params) => ipcRenderer.invoke("youle:listMaterials", params),
  listArtifacts: (params) => ipcRenderer.invoke("youle:listArtifacts", params),
  listMarketplaceSkills: (params) => ipcRenderer.invoke("youle:listMarketplaceSkills", params),
  listSkillCategories: () => ipcRenderer.invoke("youle:listSkillCategories"),
  getMarketplaceSkill: (params) => ipcRenderer.invoke("youle:getMarketplaceSkill", params),
  listMySkills: (params) => ipcRenderer.invoke("youle:listMySkills", params),
  startSkillInstall: (params) => ipcRenderer.invoke("youle:startSkillInstall", params),
  installMarketplaceSkill: (params) => ipcRenderer.invoke("youle:installMarketplaceSkill", params),
  uninstallMarketplaceSkill: (params) => ipcRenderer.invoke("youle:uninstallMarketplaceSkill", params),
  getSkillInstallation: (params) => ipcRenderer.invoke("youle:getSkillInstallation", params),
  importSkillFile: (params) => ipcRenderer.invoke("youle:importSkillFile", params),
  uploadMaterialFile: (params) => ipcRenderer.invoke("youle:uploadMaterialFile", params),
  generateVideo: (params) => ipcRenderer.invoke("youle:generateVideo", params),
  resumeVideo: (params) => ipcRenderer.invoke("youle:resumeVideo", params),
  interruptVideoGeneration: (params) => ipcRenderer.invoke("youle:interruptVideoGeneration", params),
  listAutoTasks: () => ipcRenderer.invoke("youle:listAutoTasks"),
  saveAutoTasks: (params) => ipcRenderer.invoke("youle:saveAutoTasks", params),
  runAutoTask: (params) => ipcRenderer.invoke("youle:runAutoTask", params),
  previewFile: (params) => ipcRenderer.invoke("youle:previewFile", params),
  previewImageFile: (params) => ipcRenderer.invoke("youle:previewImageFile", params),
  copyAttachmentToClipboard: (params) => ipcRenderer.invoke("youle:copyAttachmentToClipboard", params),
  localFileInfo: (params) => ipcRenderer.invoke("youle:localFileInfo", params),
  localPathInfo: (params) => ipcRenderer.invoke("youle:localPathInfo", params),
  openLocalFile: (params) => ipcRenderer.invoke("youle:openLocalFile", params),
  revealLocalFile: (params) => ipcRenderer.invoke("youle:revealLocalFile", params),
  readLocalFile: (params) => ipcRenderer.invoke("youle:readLocalFile", params),
  startFileDrag: (params) => ipcRenderer.send("youle:startFileDrag", params),
  readClipboardForComposer: () => ipcRenderer.invoke("youle:readClipboardForComposer"),
  pasteFocusedElement: () => ipcRenderer.invoke("youle:pasteFocusedElement"),
  getVoiceTranscriptionAvailability: () => ipcRenderer.invoke("voice:getAvailability"),
  startVoiceTranscription: (params) => ipcRenderer.invoke("voice:startSession", params),
  sendVoiceAudioChunk: (params) => ipcRenderer.invoke("voice:sendAudio", params),
  finishVoiceTranscription: (params) => ipcRenderer.invoke("voice:finishSession", params),
  cancelVoiceTranscription: (params) => ipcRenderer.invoke("voice:cancel", params),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  annotateImage: (params) => ipcRenderer.invoke("youle:annotateImage", params),
  listThreads: (params) => ipcRenderer.invoke("codex:listThreads", params),
  getTradingPreferenceProfile: () => ipcRenderer.invoke("personalContext:getTradingPreferences"),
  saveTradingPreferenceProfile: (params) => ipcRenderer.invoke("personalContext:saveTradingPreferences", params),
  modelList: () => ipcRenderer.invoke("codex:modelList"),
  configRead: () => ipcRenderer.invoke("codex:configRead"),
  skillsList: (params) => ipcRenderer.invoke("codex:skillsList", params),
  pluginsList: (params) => ipcRenderer.invoke("codex:pluginsList", params),
  setPluginEnabled: (params) => ipcRenderer.invoke("codex:setPluginEnabled", params),
  deletePlugin: (params) => ipcRenderer.invoke("codex:deletePlugin", params),
  getChromeIntegrationStatus: () => ipcRenderer.invoke("chrome:getStatus"),
  repairChromeIntegration: () => ipcRenderer.invoke("chrome:repair"),
  openChromeExtensions: () => ipcRenderer.invoke("chrome:openExtensions"),
  revealChromeExtension: () => ipcRenderer.invoke("chrome:revealExtension"),
  selectChromeArtifact: (params) => ipcRenderer.invoke("chrome:selectArtifact", params),
  approveChromeRequest: (params) => ipcRenderer.invoke("chrome:approve", params),
  rejectChromeRequest: (params) => ipcRenderer.invoke("chrome:reject", params),
  startThread: (params) => ipcRenderer.invoke("codex:startThread", params),
  persistTradingTranscript: (params) => ipcRenderer.invoke("codex:persistTradingTranscript", params),
  stageContinuationPrompt: (params) => ipcRenderer.invoke("codex:stageContinuationPrompt", params),
  discardSupersededContinuations: (params) => ipcRenderer.invoke("codex:discardSupersededContinuations", params),
  createContinuationThread: (params) => ipcRenderer.invoke("codex:createContinuationThread", params),
  listContinuationTransactions: (params) => ipcRenderer.invoke("codex:listContinuationTransactions", params),
  readThreadForBackgroundHydration: (params) => ipcRenderer.invoke("codex:readThreadForBackgroundHydration", params),
  resumeThread: (params) => ipcRenderer.invoke("codex:resumeThread", params),
  updateThreadSettings: (params) => ipcRenderer.invoke("codex:updateThreadSettings", params),
  compactThread: (params) => ipcRenderer.invoke("codex:compactThread", params),
  archiveThread: (params) => ipcRenderer.invoke("codex:archiveThread", params),
  prepareThreadReferences: (params) => ipcRenderer.invoke("codex:prepareThreadReferences", params),
  sendMessage: (params) => ipcRenderer.invoke("codex:sendMessage", params),
  recoverUnavailableLocalProxy: (params) => ipcRenderer.invoke("codex:recoverUnavailableLocalProxy", params),
  steerTurn: (params) => ipcRenderer.invoke("codex:steerTurn", params),
  interruptTurn: (params) => ipcRenderer.invoke("codex:interruptTurn", params),
  respondServerRequest: (params) => ipcRenderer.invoke("codex:respondServerRequest", params),
  automationList: () => ipcRenderer.invoke("automation:list"),
  automationCreateJob: (params) => ipcRenderer.invoke("automation:createJob", params),
  automationUpdateJob: (params) => ipcRenderer.invoke("automation:updateJob", params),
  automationDeleteJob: (params) => ipcRenderer.invoke("automation:deleteJob", params),
  automationPauseJob: (params) => ipcRenderer.invoke("automation:pauseJob", params),
  automationResumeJob: (params) => ipcRenderer.invoke("automation:resumeJob", params),
  automationRunNow: (params) => ipcRenderer.invoke("automation:runNow", params),
  automationCancelRun: (params) => ipcRenderer.invoke("automation:cancelRun", params),
  automationGetRun: (params) => ipcRenderer.invoke("automation:getRun", params),
  automationStartWorker: () => ipcRenderer.invoke("automation:startWorker"),
  automationStopWorker: () => ipcRenderer.invoke("automation:stopWorker"),
  automationValidateSchedule: (params) => ipcRenderer.invoke("automation:validateSchedule", params),
  automationValidateEnvironment: () => ipcRenderer.invoke("automation:validateEnvironment"),
  automationCreateDraft: (params) => ipcRenderer.invoke("automation:createDraft", params),
  automationCreateFanoutDrafts: (params) => ipcRenderer.invoke("automation:createFanoutDrafts", params),
  automationDeliverWebhook: (params) => ipcRenderer.invoke("automation:deliverWebhook", params),
  automationRegisterLoginTask: (params) => ipcRenderer.invoke("automation:registerLoginTask", params),
  automationUnregisterLoginTask: (params) => ipcRenderer.invoke("automation:unregisterLoginTask", params),
  tradingAlertsSnapshot: () => ipcRenderer.invoke("tradingAlerts:snapshot"),
  tradingAlertsGetSimulation: (params) => ipcRenderer.invoke("tradingAlerts:getSimulation", params),
  tradingAlertsCompile: (params) => ipcRenderer.invoke("tradingAlerts:compile", params),
  tradingAlertsResumeDraft: (params) => ipcRenderer.invoke("tradingAlerts:resumeDraft", params),
  tradingAlertsSimulate: (params) => ipcRenderer.invoke("tradingAlerts:simulate", params),
  tradingAlertsConfirm: (params) => ipcRenderer.invoke("tradingAlerts:confirm", params),
  tradingAlertsSyncExecutionPlan: (params) => ipcRenderer.invoke("tradingAlerts:syncExecutionPlan", params),
  tradingAlertsRevise: (params) => ipcRenderer.invoke("tradingAlerts:revise", params),
  tradingAlertsPause: (params) => ipcRenderer.invoke("tradingAlerts:pause", params),
  tradingAlertsResume: (params) => ipcRenderer.invoke("tradingAlerts:resume", params),
  tradingAlertsDelete: (params) => ipcRenderer.invoke("tradingAlerts:delete", params),
  tradingAlertsLifecycle: (params) => ipcRenderer.invoke("tradingAlerts:lifecycle", params),
  tradingAlertsSyncDrawings: (params) => ipcRenderer.invoke("tradingAlerts:syncDrawings", params),
  tradingAlertsMarketSubscribe: (params) => ipcRenderer.invoke("tradingAlerts:marketSubscribe", params),
  tradingAlertsMarketUnsubscribe: (params) => ipcRenderer.invoke("tradingAlerts:marketUnsubscribe", params),
  openExternal: (url) => ipcRenderer.invoke("codex:openExternal", url),
  openBlockchainTransaction: (params) => ipcRenderer.invoke("youle:openBlockchainTransaction", params),
  debugLog: (params) => ipcRenderer.invoke("youle:debugLog", params),
  captureTradingChart: (params) => ipcRenderer.invoke("trading:captureChart", params),
  windowControl: (action) => ipcRenderer.invoke("window:control", action),
  windowMove: (params) => ipcRenderer.invoke("window:move", params),
  windowMoveLive: (params) => ipcRenderer.send("window:move-live", params),
  windowResize: (params) => ipcRenderer.invoke("window:resize", params),
  windowResizeLive: (params) => ipcRenderer.send("window:resize-live", params),
  setWindowMode: (mode, options) => ipcRenderer.invoke("window:setMode", mode, options),
  getWindowState: () => ipcRenderer.invoke("window:getState"),
  revealWindowModeTransition: () => ipcRenderer.invoke("window:revealModeTransition"),
  onStatus: (callback) => on("codex:status", callback),
  onLog: (callback) => on("codex:log", callback),
  onNotification: (callback) => on("codex:notification", callback),
  onSkills: (callback) => on("codex:skills", callback),
  onChromeStatus: (callback) => on("chrome:status", callback),
  onChromeIntegration: (callback) => on("chrome:integration", callback),
  onChromeTask: (callback) => on("chrome:task", callback),
  onChromeApproval: (callback) => on("chrome:approval", callback),
  onChromeApprovalUpdated: (callback) => on("chrome:approvalUpdated", callback),
  onLocalArtifactsChanged: (callback) => on("youle:localArtifactsChanged", callback),
  onAutoTasksChanged: (callback) => on("youle:autoTasksChanged", callback),
  onChannelEvent: (callback) => on("youle:channelEvent", callback),
  onExternalChannelsBackendReady: (callback) => on("youle:externalChannelsBackendReady", callback),
  onProfileUpdated: (callback) => on("youle:profileUpdated", callback),
  onAuthExpired: (callback) => on("youle:authExpired", callback),
  onWindowsUpdateDownloadProgress: (callback) => on("app:windowsUpdateDownloadProgress", callback),
  onAppConfirmationRequested: (callback) => on("app:confirmation-request", callback),
  onVoiceInputStop: (callback) => on("voice:stopCapture", callback),
  onVoiceTranscriptionResult: (callback) => on("voice:result", callback),
  onServerRequest: (callback) => on("codex:serverRequest", callback),
  onAutomationChanged: (callback) => on("automation:changed", callback),
  onAutomationOpenRun: (callback) => on("automation:openRun", callback),
  onAutomationOpenThread: (callback) => on("automation:openThread", callback),
  onAutomationThreadNotification: (callback) => on("automation:threadNotification", callback),
  onTradingAlertsChanged: (callback) => on("tradingAlerts:changed", callback),
  onTradingStrategyProgress: (callback) => on("tradingStrategy:progress", callback),
  onTradingAlertIntentProgress: (callback) => on("tradingAlerts:intentProgress", callback),
  onTradingAlertTriggered: (callback) => on("tradingAlerts:triggered", callback),
  onTradingAlertOpen: (callback) => on("tradingAlerts:open", callback),
  onTradingAlertMarketData: (callback) => on("tradingAlerts:marketData", callback),
  onError: (callback) => on("codex:error", callback),
  onWindowState: (callback) => on("window:state", callback),
  onOpenSettings: (callback) => on("app:openSettings", callback),
});
